### PR TITLE
feat(config): option to keep last known state

### LINKED ISSUE #43: Loss my AC after update to msmart==0.1.24
**Describe the bug （描述一下问题）**
Hi, Mac.

After the last update to version msmart==0.1.24 (I updated on 12/01/2020), I get constant disappearing of my air conditioners. I see it in Logbook and History. There are no records of this in the Logs. Only once, right after the update:

```
Log Details (ERROR)
Logger: homeassistant.components.websocket_api.http.connection
Source: core.py:1405
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: December 1, 2020, 9:04:03 AM (1 occurrences)
Last logged: December 1, 2020, 9:04:03 AM

[140718739954560] string value is None for dictionary value @ data['preset_mode']
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 135, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1405, in async_call
    processed_data = handler.schema(service_data)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 218, in __call__
    return self._exec((Schema(val) for val in self.validators), v)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 340, in _exec
    raise e if self.msg is None else AllInvalid(self.msg, path=path)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 336, in _exec
    v = func(v)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable
    return schema(data)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: string value is None for dictionary value @ data['preset_mode']
```
Before that, on version msmart==0.1.23 this was not. Everything worked fine and stable for a few months.

**Screenshots / Logs / Pcap File（屏幕截图/日志/抓包文件）**
midea_ac_drop

midea_ac_drop1

请提交相关截图，日志，抓包让开发者能够更快的解决问题

**Versions (版本信息)**
 - Home Assistant version: 0.118.4
 - Midea msmart version: ==0.1.24
 - My air conditioners: Midea Midea Mission II MB-09N8D6H-I/MB-09N8D6H-O and Midea Mission II MB-12N8D6H-I/MB-12N8D6H-O
 - Wi-Fi module SK-102

Thanks.

### PR DESCRIPTION
**Pull request by rokam**
Fixes #43 #62

### CODE REVIEW

**Review by mac-zhou — CHANGES_REQUESTED** [review]
1. the option name should be the same as `msmart`
2. set the option value can be after client.setup(), like `device._keep_last_known_state = keep_last_known_state`

**Comment by rokam** [comment]
So, should I remove it from the constructor at msmart?

**Comment by rokam** [comment]
@mac-zhou any additional request?

**Comment by rokam** [comment]
@mac-zhou bump

**Pull request merged**
